# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\messenger_chat_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ChatWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(ChatWindow, self).__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(480, 817)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.send_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_btn.setGeometry(QtCore.QRect(170, 640, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.send_btn.setFont(font)
        self.send_btn.setObjectName("send_btn")
        self.choose_file_btn = QtWidgets.QPushButton(self.centralwidget)
        self.choose_file_btn.setGeometry(QtCore.QRect(10, 640, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.choose_file_btn.setFont(font)
        self.choose_file_btn.setObjectName("choose_file_btn")
        self.multicast_btn = QtWidgets.QPushButton(self.centralwidget)
        self.multicast_btn.setGeometry(QtCore.QRect(330, 640, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.multicast_btn.setFont(font)
        self.multicast_btn.setObjectName("multicast_btn")
        self.msg_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.msg_text.setGeometry(QtCore.QRect(10, 520, 461, 111))
        self.msg_text.setObjectName("msg_text")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(5, 1, 471, 501))
        self.listWidget.setObjectName("listWidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(7, 500, 461, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        self.listWidget.setSpacing(5)

        scroll = QtWidgets.QScrollBar()
        self.listWidget.setVerticalScrollBar(scroll)
        self.listWidget.setWordWrap(True)

        self.send_btn.setStyleSheet('background-color:green; color:white')

    def retranslateUi(self, ChatWindow):
        _translate = QtCore.QCoreApplication.translate
        ChatWindow.setWindowTitle(_translate("ChatWindow", "ChatWindow"))
        self.send_btn.setText(_translate("ChatWindow", "Wyślij"))
        self.choose_file_btn.setText(_translate("ChatWindow", "Wyślij obraz"))
        self.multicast_btn.setText(_translate("ChatWindow", "Multicast"))

    def validate(self):
        return self.msg_text.toPlainText()
